# ML Assignment 2: Banknote classification
# https://archive.ics.uci.edu/ml/datasets/banknote+authentication
# Goto the link above for Problem statement, dataset and its description. 
# Solve this problem using Logistic regression, KNN. Compare accuracy and upload pdf file of code.

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
df = pd.read_csv('../DataSets/data_banknote_authentication.txt')

In [3]:
df.head()

3.6216  8.6661  -2.8073  -0.44699  0
0  4.54590  8.1674  -2.4586  -1.46210  0
1  3.86600 -2.6383   1.9242   0.10645  0
2  3.45660  9.5228  -4.0112  -3.59440  0
3  0.32924 -4.4552   4.5718  -0.98880  0
4  4.36840  9.6718  -3.9606  -3.16250  0

In [4]:
df = pd.read_csv('../DataSets/data_banknote_authentication.txt', header = None)

In [5]:
df.head()

0       1       2        3  4
0  3.62160  8.6661 -2.8073 -0.44699  0
1  4.54590  8.1674 -2.4586 -1.46210  0
2  3.86600 -2.6383  1.9242  0.10645  0
3  3.45660  9.5228 -4.0112 -3.59440  0
4  0.32924 -4.4552  4.5718 -0.98880  0

In [6]:
# OR

In [7]:
header_list = ["variance of Wavelet Transformed image", "skewness of Wavelet Transformed image", "curtosis of Wavelet Transformed image", "entropy of image", "class"]

In [8]:
df = pd.read_csv("../DataSets/data_banknote_authentication.txt", names = header_list)

In [9]:
df.head()

variance of Wavelet Transformed image  \
0                                3.62160   
1                                4.54590   
2                                3.86600   
3                                3.45660   
4                                0.32924   

   skewness of Wavelet Transformed image  \
0                                 8.6661   
1                                 8.1674   
2                                -2.6383   
3                                 9.5228   
4                                -4.4552   

   curtosis of Wavelet Transformed image  entropy of image  class  
0                                -2.8073          -0.44699      0  
1                                -2.4586          -1.46210      0  
2                                 1.9242           0.10645      0  
3                                -4.0112          -3.59440      0  
4                                 4.5718          -0.98880      0

In [10]:
list_of_column_names = list(df.columns)

In [11]:
print('List of column names : ', list_of_column_names)

List of column names :  ['variance of Wavelet Transformed image', 'skewness of Wavelet Transformed image', 'curtosis of Wavelet Transformed image', 'entropy of image', 'class']


In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1372 entries, 0 to 1371
Data columns (total 5 columns):
 #   Column                                 Non-Null Count  Dtype  
---  ------                                 --------------  -----  
 0   variance of Wavelet Transformed image  1372 non-null   float64
 1   skewness of Wavelet Transformed image  1372 non-null   float64
 2   curtosis of Wavelet Transformed image  1372 non-null   float64
 3   entropy of image                       1372 non-null   float64
 4   class                                  1372 non-null   int64  
dtypes: float64(4), int64(1)
memory usage: 53.7 KB


In [13]:
df['class']

0       0
1       0
2       0
3       0
4       0
       ..
1367    1
1368    1
1369    1
1370    1
1371    1
Name: class, Length: 1372, dtype: int64

In [14]:
df.shape

(1372, 5)

In [15]:
X = df[['variance of Wavelet Transformed image', 'skewness of Wavelet Transformed image', 'curtosis of Wavelet Transformed image', 'entropy of image']]
y = df['class']

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=8)

In [18]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((1029, 4), (343, 4), (1029,), (343,))

In [19]:
from sklearn.preprocessing import MinMaxScaler

scalar = MinMaxScaler()

In [20]:
scalar.fit(X_train)

MinMaxScaler()

In [21]:
scalar.data_max_

array([ 6.8248, 12.6247, 17.9274,  2.4495])

In [22]:
scalar.data_min_

array([ -7.0421, -13.7731,  -5.2613,  -8.5482])

In [23]:
X_train_scaled = scalar.transform(X_train)
X_test_scaled = scalar.transform(X_test)

# 1. Logistic Regression

In [24]:
from sklearn.linear_model import LogisticRegression

In [25]:
model = LogisticRegression()

In [26]:
model.fit(X_train_scaled, y_train)

LogisticRegression()

In [27]:
model.score(X_train_scaled, y_train), model.score(X_test_scaled, y_test), 

(0.9698736637512148, 0.967930029154519)

In [28]:
# code for client to test model

In [29]:
q0 = [['5.45660', '-12.5228', '9.0112', '1.59440']]
q0_scaled = scalar.transform(q0)
model.predict(q0_scaled)

array([0], dtype=int64)

In [30]:
def get_predict(q0):
    q0_scaled = scalar.transform(q0)
    yp = model.predict(q0_scaled)
    return '0' if yp==0 else '1'

In [31]:
q1 = [['5.45660', '-12.5228', '-9.0112', '-1.59440']]

get_predict(q1)

'1'

# 2. KNN Classifier

In [32]:
from sklearn.neighbors import KNeighborsClassifier

In [33]:
model_1 = KNeighborsClassifier()

In [34]:
model_1.fit(X_train_scaled, y_train)

KNeighborsClassifier()

In [35]:
model_1.score(X_train_scaled, y_train), model_1.score(X_test_scaled, y_test)

(0.9980563654033042, 1.0)

# Accuracy Comparison of Logistic Regression and KNN model

In [36]:
# 1. Logistic Regression
#    Test score = 0.9737609329446064

# 2. KNN Classifier
#    Test score = 1.0

In [37]:
# It is observed that the accuracy for KNN model is more than Logistic Regression model for given data set